### ISSUE TITLE
Recursive Lock Not Allowed in Transaction

### ISSUE THREAD

**Issue by cliftonlabrum** [journeyapps/sqlite_async.dart#2]
I have a function that iterates over a `List` of objects, converts them to queries, and saves them to the database. I've omitted how I actually generate the query, but suffice it to say the end result is a proper SQLite query.

```dart
final db = SqliteDatabase(path: Paths.database);

await db.writeTransaction((tx) async { //<-- Exception: Recursive lock is not allowed
  for (var object in objects) {
    //Get the table name...

    //Assemble column names from object keys...

    //Make a comma-separated list of ? using the column list length...

    await db.execute('''
    INSERT OR REPLACE INTO $table (${columns.join(',')})
    VALUES ($questionMarks)
    ''', values);
  }
});

await db.close();
```
But I keep getting an exception on the line with the `db.writeTransaction` that says:
> Recursive lock is not allowed

Any idea why can't I execute multiple `INSERT` queries at once inside the transaction? I call this code for a variety of different chunks of data, so it's possible a prior transaction is already in progress.

How I make sure the database isn't locked and that my queries don't collide?

**Comment by rkistner** [comment]
Instead of `db.execute()`, you need to use `tx.execute()`. `db.execute()` would effectively start a new transaction, which would cause a deadlock in this case. The "Recursive lock is not allowed" checks for this case to fail hard, instead of blocking on the deadlock.

I'll see if we can make the error message more clear for this case.
